# -*- coding: utf-8 -*-
"""ode.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10dgXJ8ogG-cieIN5ONWL9R6Vv05SRvU9
"""

import numpy as np

def double_pendulum_ode(t, z, L1, L2, m1, m2, g):
    """
    Calculates the time derivatives for the double pendulum system.

    State vector:
        z = [theta1, omega1, theta2, omega2]

    Returns:
        [dtheta1/dt, domega1/dt, dtheta2/dt, domega2/dt]
    """
    theta1, omega1, theta2, omega2 = z
    delta = theta1 - theta2

    cos_d = np.cos(delta)
    sin_d = np.sin(delta)

    # Shared gravitational term
    g_term = (m1 + m2) * g * np.sin(theta1)

    # Denominator term
    eta = m2 * cos_d**2 - (m1 + m2)

    # Angular accelerations
    d_omega1 = (
        L1 * m2 * cos_d * sin_d * omega1**2 +
        L2 * m2 * sin_d * omega2**2 -
        m2 * g * cos_d * np.sin(theta2) +
        g_term
    ) / (L1 * eta)

    d_omega2 = -(
        L2 * m2 * cos_d * sin_d * omega2**2 +
        L1 * (m1 + m2) * sin_d * omega1**2 +
        g_term * cos_d -
        (m1 + m2) * g * np.sin(theta2)
    ) / (L2 * eta)

    return omega1, d_omega1, omega2, d_omega2