# -*- coding: utf-8 -*-
"""utils.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12DjeyWW7q562cZxVFSlJ-maHxq88SW05
"""

import numpy as np

def to_cartesian_state(traj, L1, L2):
    """
    Converts an angular trajectory into Cartesian positions and velocities.

    Input:
        traj: array of shape (T, 4)
              [theta1, omega1, theta2, omega2]

    Returns:
        state: array of shape (T, 8)
               [x1, y1, x2, y2, vx1, vy1, vx2, vy2]
    """
    out = []

    for theta1, omega1, theta2, omega2 in traj:
        # First mass position
        x1 = L1 * np.sin(theta1)
        y1 = -L1 * np.cos(theta1)

        # Second mass position
        x2 = x1 + L2 * np.sin(theta2)
        y2 = y1 - L2 * np.cos(theta2)

        # Velocities
        vx1 = L1 * np.cos(theta1) * omega1
        vy1 = L1 * np.sin(theta1) * omega1

        vx2 = vx1 + L2 * np.cos(theta2) * omega2
        vy2 = vy1 + L2 * np.sin(theta2) * omega2

        out.append([x1, y1, x2, y2, vx1, vy1, vx2, vy2])

    return np.array(out)